### ISSUE TITLE
包含UIWebView的ipa将会被禁止上架苹果应用商店

### ISSUE THREAD

**Issue by esdotzed** [1556173267/react-native-mob-sms#3]
我在上传一个测试包到苹果时发现收到这个邮件。

Dear Developer,

We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Binary file node_modules/@superhao/react-native-mob-sms/ios/ReactNativeMobSMS/MOBFoundation/MOBFoundation.a matches
node_modules/@superhao/react-native-mob-sms/ios/ReactNativeMobSMS/MOBFoundation/MOBFJSContext.h:- (instancetype)initWithWebView:(UIWebView *)webview;

苹果很可能很快要禁止用这个包的应用上架了。。

**Comment by esdotzed** [comment]
请问这个问题有解决办法吗？今年年底就是最后期限了哦。

**Comment by esdotzed** [comment]
@1556173267 ^

**Comment by 1556173267** [comment]
我更新一下版本 @esdotzed

**Comment by 1556173267** [comment]
@esdotzed 已更新版本

**Comment by esdotzed** [comment]
非常感谢！如此迅速的修复！我已经打包重新提交App store了，万分感谢！！！！！

**Comment by esdotzed** [comment]
@1556173267 ^
